### ISSUE TITLE
Undefined index error

### ISSUE THREAD

**Issue by zivelli** [jehy/wp-noexternallinks#1]
I keep getting the following notice in my debug.log

PHP Notice:  Undefined index: wp_noextrenallinks_noncename in /home/qweqw/public_html/wp-content/plugins/wp-noexternallinks/wp-noexternallinks-options.php on line 20

This is occurring in function save_postdata and appears in groups where the error repeats 10 or 40 times.

Thnxs

**Comment by jehy** [comment]
Hello. Plugin is not designed for running with PHP notices on. That's not an error.

**Comment by zivelli** [comment]
Thanks for the reply.

I'm running the debugger while building a wp theme. So of course I observed the "PHP Notice:Undefined index error" was appearing quite often.

If its not an error with wp_verify_nonce than I'll ignore.

Thnxs again for your great work on the plugin.
