### ISSUE TITLE
Encode Base64

### ISSUE THREAD

**Issue by dokxpi** [jehy/wp-noexternallinks#2]
Доброго времени суток
Подскажите пожалуйста, 
что нужно сделать для того, чтобы получить внешние ссылки следующего вида: `http://mysite.com/out/aHR0cHM6Ly9naXRodWIuY29tL2plaHkvd3Atbm9leHRlcm5hbGxpbmtz`
где `aHR0cHM6Ly9naXRodWIuY29tL2plaHkvd3Atbm9leHRlcm5hbGxpbmtz` внешняя ссылка обернута в base64

> decode Base64 (`aHR0cHM6Ly9naXRodWIuY29tL2plaHkvd3Atbm9leHRlcm5hbGxpbmtz` )
> https://github.com/jehy/wp-noexternallinks

**http://mysite.com/out/** + external links base64

**Comment by dokxpi** [comment]
Сразу не добрался до настроек, поврежденный .htaccess не дал этого сделать 
Спасибо, вопрос закрыт

Плагин супер

**Comment by jehy** [comment]
@dokxpi Отлично : )
