### ISSUE TITLE
exclude sitemap or just allow a few url specified

### ISSUE THREAD

**Issue by MojtabaFaal** [jehy/wp-noexternallinks#3]
hi @jehy 
in plugin WP-NoExternalLinks
how to **exclude** sitemap_index.xml
Excluding sitemap_index.xml and all the links within sitemap_index.xml
or just **allow** a few url specified
I’m using Yoast
thanks

**Comment by MojtabaFaal** [comment]
and please add box only allow URL

**Comment by jehy** [comment]
Hello! If your sitemap's links begin from your blog's domain, those should not be included.
If there are links to pages on another domain, you could use whitelist to specify this domain.
