### ISSUE TITLE
Doesn't work with ajax

### ISSUE THREAD

**Issue by zlecenie** [jehy/wp-noexternallinks#5]
Hi,

The plugin doesn't work with ajax.

I believe the problem is that the plugin does not apply its filter to the content when is_admin is true https://plugins.trac.wordpress.org/browser/wp-noexternallinks/trunk/public/public.php#L164

This is a problem because the filters of FacetWP plugin run in an ajax request and is_admin is always true during an ajax request. The plugin has not accounted for content that is updated with ajax.

I tried to change it to:
if ( function_exists( 'is_admin' ) && is_admin() && ! wp_doing_ajax() ) {
but nothing happens...

https://facetwp.com/is_admin-and-ajax-in-wordpress/

**Comment by jehy** [comment]
Hi! I no longer support this plugin, so you can report this on plugin's page on wordpress and may be current maintainer will help you.
